// Layout definitions — hero variants, section alignment, padding, heading sizes.
// Each layout is a complete visual style preset selectable in the Design tab.

export const LAYOUTS = [
  {
    id: "editorial-minimal",
    name: "Editorial Minimal",
    headingFont: "Yeseva One",
    bodyFont: "DM Sans",
    desc: "Standard hero, generous grid services. Restraint, work-first. Rosalie, Lustre, Breef.",
    heroVariant: "left-standard",
    servicesVariant: "grid-numbered",
    heroAlign: "left",
    heroPadding: 140,
    heroHeading: 84,
    sectionPadding: 100,
    sectionHeading: 48,
    sectionAlign: "left",
    eyebrowStyle: "dot",
    cardRadius: 0,
    aboutLayout: "split",
  },
  {
    id: "editorial-bold",
    name: "Editorial Bold",
    headingFont: "Manrope",
    bodyFont: "Inter",
    desc: "Split hero with image, services as full-width list rows. Faure, Nevo.",
    heroVariant: "split-image",
    servicesVariant: "list-row",
    heroAlign: "left",
    heroPadding: 100,
    heroHeading: 96,
    sectionPadding: 100,
    sectionHeading: 64,
    sectionAlign: "left",
    eyebrowStyle: "lower",
    cardRadius: 0,
    aboutLayout: "split",
  },
  {
    id: "magazine",
    name: "Magazine",
    headingFont: "Playfair Display",
    bodyFont: "Inter",
    desc: "Centered hero, services with huge serif numbers. Print-editorial feel.",
    heroVariant: "centered-bold",
    servicesVariant: "serif-stack",
    heroAlign: "center",
    heroPadding: 160,
    heroHeading: 88,
    sectionPadding: 120,
    sectionHeading: 56,
    sectionAlign: "center",
    eyebrowStyle: "number",
    cardRadius: 0,
    aboutLayout: "stacked",
  },
  {
    id: "studio-modern",
    name: "Studio Modern",
    headingFont: "Inter",
    bodyFont: "Inter",
    desc: "Split rounded hero, services in soft rounded cards. Modern, tech-forward.",
    heroVariant: "split-image-rounded",
    servicesVariant: "cards-padded",
    heroAlign: "left",
    heroPadding: 100,
    heroHeading: 64,
    sectionPadding: 100,
    sectionHeading: 40,
    sectionAlign: "center",
    eyebrowStyle: "upper",
    cardRadius: 16,
    aboutLayout: "split",
  },
  {
    id: "brutalist",
    name: "Brutalist",
    headingFont: "Oswald",
    bodyFont: "Inter",
    desc: "Hero is just massive overflowing text. Services as raw list rows. Experimental.",
    heroVariant: "minimal-text",
    servicesVariant: "list-row",
    heroAlign: "left",
    heroPadding: 60,
    heroHeading: 144,
    sectionPadding: 80,
    sectionHeading: 80,
    sectionAlign: "left",
    eyebrowStyle: "bracket",
    cardRadius: 0,
    aboutLayout: "split",
  },
  {
    id: "swiss-grid",
    name: "Swiss Grid",
    headingFont: "Inter",
    bodyFont: "Inter",
    desc: "Clean Helvetica-style grid system. Corporate polish without flair. B2B, professional services, consulting.",
    heroVariant: "split-image",
    servicesVariant: "grid-numbered",
    heroAlign: "left",
    heroPadding: 120,
    heroHeading: 72,
    sectionPadding: 120,
    sectionHeading: 44,
    sectionAlign: "left",
    eyebrowStyle: "upper",
    cardRadius: 0,
    aboutLayout: "split",
  },
  {
    id: "boutique-luxury",
    name: "Boutique Luxury",
    headingFont: "Cormorant Garamond",
    bodyFont: "Inter",
    desc: "Thin italic serif, ultra-spacious, refined. Hotels, jewelry, fashion houses, luxury hospitality.",
    heroVariant: "centered-bold",
    servicesVariant: "serif-stack",
    heroAlign: "center",
    heroPadding: 180,
    heroHeading: 92,
    sectionPadding: 140,
    sectionHeading: 52,
    sectionAlign: "center",
    eyebrowStyle: "upper",
    cardRadius: 0,
    aboutLayout: "stacked",
  },
  {
    id: "apple-minimal",
    name: "Apple Minimal",
    headingFont: "Inter",
    bodyFont: "Inter",
    desc: "Centered sans, image-led, extreme whitespace. Product brands, tech startups, premium consumer goods.",
    heroVariant: "centered-bold",
    servicesVariant: "cards-padded",
    heroAlign: "center",
    heroPadding: 140,
    heroHeading: 80,
    sectionPadding: 120,
    sectionHeading: 56,
    sectionAlign: "center",
    eyebrowStyle: "upper",
    cardRadius: 16,
    aboutLayout: "stacked",
  },
  {
    id: "modern-tech",
    name: "Modern Tech",
    headingFont: "Manrope",
    bodyFont: "Inter",
    desc: "Bold sans with gradient-friendly accents. SaaS, fintech, AI startups, dev platforms.",
    heroVariant: "split-image",
    servicesVariant: "cards-padded",
    heroAlign: "left",
    heroPadding: 110,
    heroHeading: 88,
    sectionPadding: 100,
    sectionHeading: 56,
    sectionAlign: "left",
    eyebrowStyle: "upper",
    cardRadius: 12,
    aboutLayout: "split",
  },
  {
    id: "mono-terminal",
    name: "Mono Terminal",
    headingFont: "Space Mono",
    bodyFont: "Space Mono",
    desc: "Monospace technical aesthetic with bracket eyebrows. Dev tools, AI infra, technical documentation, indie tech.",
    heroVariant: "left-standard",
    servicesVariant: "list-row",
    heroAlign: "left",
    heroPadding: 100,
    heroHeading: 64,
    sectionPadding: 80,
    sectionHeading: 36,
    sectionAlign: "left",
    eyebrowStyle: "bracket",
    cardRadius: 0,
    aboutLayout: "split",
  },
  {
    id: "wedding-editorial",
    name: "Wedding Editorial",
    headingFont: "Cormorant Garamond",
    bodyFont: "Inter",
    desc: "Romantic serif with extreme spaciousness. Wedding photography, hospitality, events, lifestyle weddings.",
    heroVariant: "fullbleed-overlay",
    servicesVariant: "serif-stack",
    heroAlign: "center",
    heroPadding: 200,
    heroHeading: 80,
    sectionPadding: 140,
    sectionHeading: 48,
    sectionAlign: "center",
    eyebrowStyle: "upper",
    cardRadius: 0,
    aboutLayout: "stacked",
  },
  {
    id: "literary-warm",
    name: "Literary Warm",
    headingFont: "Fraunces",
    bodyFont: "DM Sans",
    desc: "Soft literary serif with a warm, modern body. Journalism, publishing, thoughtful service brands, storytellers.",
    heroVariant: "left-standard",
    servicesVariant: "serif-stack",
    heroAlign: "left",
    heroPadding: 140,
    heroHeading: 80,
    sectionPadding: 120,
    sectionHeading: 48,
    sectionAlign: "left",
    eyebrowStyle: "dot",
    cardRadius: 0,
    aboutLayout: "split",
  },
  {
    id: "haute-editorial",
    name: "Haute Editorial",
    headingFont: "Italiana",
    bodyFont: "Be Vietnam Pro",
    desc: "Tall elegant display with a clean modern body. Fashion, beauty, high-end creative studios, luxury retail.",
    heroVariant: "centered-bold",
    servicesVariant: "serif-stack",
    heroAlign: "center",
    heroPadding: 160,
    heroHeading: 96,
    sectionPadding: 140,
    sectionHeading: 56,
    sectionAlign: "center",
    eyebrowStyle: "upper",
    cardRadius: 0,
    aboutLayout: "stacked",
  },
  {
    id: "geometric-studio",
    name: "Geometric Studio",
    headingFont: "Space Grotesk",
    bodyFont: "Manrope",
    desc: "Geometric sans pairing — bold, confident, purposeful. Modern agencies, design studios, brand consultancies.",
    heroVariant: "split-image",
    servicesVariant: "grid-numbered",
    heroAlign: "left",
    heroPadding: 120,
    heroHeading: 80,
    sectionPadding: 100,
    sectionHeading: 48,
    sectionAlign: "left",
    eyebrowStyle: "upper",
    cardRadius: 8,
    aboutLayout: "split",
  },
];

export const getLayout = (id) => LAYOUTS.find(l => l.id === id) || LAYOUTS[0];

// Eyebrow text formatter based on layout style
export const eyebrowText = (style, text) => {
  const u = (text || "").toUpperCase();
  const l = (text || "").toLowerCase();
  if (style === "dot") return `●  ${u}`;
  if (style === "lower") return l;
  if (style === "number") return u;
  if (style === "bracket") return `[ ${u} ]`;
  return u;
};

// ──────────────────────────────────────────────────────────────────────────────
// WEBSITE TEMPLATES — full industry-specific presets. Picking one applies layout,
// theme, accent, fonts, section composition, AND default copy in a single click.
// Each template is a complete starting point — swap copy/images and ship.
// Inspired by reference sites in the screenshots: Superside, VaynerMedia, Cohley,
// Pola Marketing, Skims, Loft, Nike, Poosh, Goop, Rosalie, Lustre.
// ──────────────────────────────────────────────────────────────────────────────