// Theme definitions — background color, card color, heading color, mode (light/dark)
// Each theme is selectable in the Design tab. Add new themes here.

export const THEMES = [
  {
    id: "editorial-dark",
    name: "Editorial Dark",
    desc: "Deep black + champagne gold. The premium editorial standard. Studios, agencies, creative.",
    mode: "dark",
    primaryColor: "#0a0a0a",
    cardBgColor: "#141414",
    accentColor: "#c9a86a",
    bodyTextColor: "#a8a8a8",
    borderColor: "#1f1f1f",
    headingColor: "#fafafa",
  },
  {
    id: "onyx-bronze",
    name: "Onyx & Bronze",
    desc: "Soft black + warm bronze. Luxury hospitality, jewelry, premium services.",
    mode: "dark",
    primaryColor: "#1a1614",
    cardBgColor: "#241f1b",
    accentColor: "#b87333",
    bodyTextColor: "#b5ab9f",
    borderColor: "#2a241f",
    headingColor: "#f5ede0",
  },
  {
    id: "midnight",
    name: "Midnight",
    desc: "Deep ink navy + soft coral. Modern tech with warmth. SaaS, fintech, B2B.",
    mode: "dark",
    primaryColor: "#0d1424",
    cardBgColor: "#161e30",
    accentColor: "#ed7464",
    bodyTextColor: "#a8b3c7",
    borderColor: "#1f2940",
    headingColor: "#ffffff",
  },
  {
    id: "espresso",
    name: "Espresso",
    desc: "Deep coffee brown + warm cream. Cozy, organic. Cafes, food, hospitality.",
    mode: "dark",
    primaryColor: "#1c1410",
    cardBgColor: "#26190f",
    accentColor: "#e8c8a0",
    bodyTextColor: "#b8a99a",
    borderColor: "#332419",
    headingColor: "#f5ebe0",
  },
  {
    id: "forest",
    name: "Forest",
    desc: "Deep forest green + warm sand. Grounded, natural. Wellness, sustainability.",
    mode: "dark",
    primaryColor: "#15241d",
    cardBgColor: "#1d2f27",
    accentColor: "#d4b896",
    bodyTextColor: "#a8b5af",
    borderColor: "#26392f",
    headingColor: "#f0ebe0",
  },
  {
    id: "pure-minimal",
    name: "Pure Minimal",
    desc: "White + pure black. Maximum contrast, gallery feel. Portfolios, art, fashion.",
    mode: "light",
    primaryColor: "#ffffff",
    cardBgColor: "#f7f7f5",
    accentColor: "#0a0a0a",
    bodyTextColor: "#4a4a4a",
    borderColor: "#e8e8e6",
    headingColor: "#0a0a0a",
  },
  {
    id: "bone-ink",
    name: "Bone & Ink",
    desc: "Bone white + deep ink navy. Editorial print feel. Publishing, consulting.",
    mode: "light",
    primaryColor: "#f3eee2",
    cardBgColor: "#e8e0d0",
    accentColor: "#1f2940",
    bodyTextColor: "#3d3a35",
    borderColor: "#d4ccb8",
    headingColor: "#1a2238",
  },
  {
    id: "linen-clay",
    name: "Linen & Clay",
    desc: "Warm linen + earthy terracotta. Artisan, approachable. Beauty, ceramics, food.",
    mode: "light",
    primaryColor: "#f8f1e7",
    cardBgColor: "#ede2d2",
    accentColor: "#a64f30",
    bodyTextColor: "#4a3a30",
    borderColor: "#dccdb8",
    headingColor: "#2a1810",
  },
  {
    id: "sage-stone",
    name: "Sage & Stone",
    desc: "Muted sage + warm stone. Calm, refined wellness. Spa, mindfulness, health.",
    mode: "light",
    primaryColor: "#f4f1ea",
    cardBgColor: "#e6e6dc",
    accentColor: "#4a5d44",
    bodyTextColor: "#4a4a42",
    borderColor: "#d4d4c8",
    headingColor: "#26302a",
  },
  {
    id: "charcoal-blush",
    name: "Charcoal & Blush",
    desc: "Soft charcoal + dusty rose. Feminine but refined. Beauty, fashion, lifestyle.",
    mode: "light",
    primaryColor: "#f8f0ec",
    cardBgColor: "#ede0d8",
    accentColor: "#3a2828",
    bodyTextColor: "#4a3a3a",
    borderColor: "#e0d0c8",
    headingColor: "#1a1010",
  },
  {
    id: "neon-mono",
    name: "Neon Mono",
    desc: "Black background with electric neon green accent. Y2K, tech, indie energy.",
    mode: "dark",
    primaryColor: "#0a0a0a",
    cardBgColor: "#141414",
    accentColor: "#39ff14",
    bodyTextColor: "#a0a0a0",
    borderColor: "#222222",
    headingColor: "#ffffff",
  },
  {
    id: "hot-pink-mono",
    name: "Hot Pink Pop",
    desc: "Crisp white with bold hot pink accent. Beauty, lifestyle, bold consumer.",
    mode: "light",
    primaryColor: "#ffffff",
    cardBgColor: "#fafafa",
    accentColor: "#ff2d87",
    bodyTextColor: "#4a4a4a",
    borderColor: "#e8e8e8",
    headingColor: "#0a0a0a",
  },
  {
    id: "slate-amber",
    name: "Slate & Amber",
    desc: "Dark cool slate + warm amber. Architecture, industrial, professional services.",
    mode: "dark",
    primaryColor: "#1a1d24",
    cardBgColor: "#22262f",
    accentColor: "#d4901a",
    bodyTextColor: "#9aa0ad",
    borderColor: "#2c3140",
    headingColor: "#f0f2f5",
  },
  {
    id: "ivory-violet",
    name: "Ivory & Violet",
    desc: "Warm ivory + muted violet. Coaches, consultants, creative agencies that want something beyond terracotta.",
    mode: "light",
    primaryColor: "#faf8f4",
    cardBgColor: "#f0edf8",
    accentColor: "#6b4fa0",
    bodyTextColor: "#4a4458",
    borderColor: "#ddd8ee",
    headingColor: "#1e1628",
  },
  {
    id: "ash-copper",
    name: "Ash & Copper",
    desc: "Cool light gray + rich copper. Interior design, real estate, premium B2B services.",
    mode: "light",
    primaryColor: "#f2f3f5",
    cardBgColor: "#e8eaed",
    accentColor: "#b05e2a",
    bodyTextColor: "#444850",
    borderColor: "#d4d8de",
    headingColor: "#1a1c20",
  },
  {
    id: "harbor-blue",
    name: "Harbor Blue",
    desc: "Deep trust navy + clean sky-blue accent. The proven pairing for law, medical, home services, and real estate — anywhere the sale depends on trust.",
    mode: "dark",
    primaryColor: "#0f1e33",
    cardBgColor: "#16283f",
    accentColor: "#3b82c4",
    bodyTextColor: "#a9b8cc",
    borderColor: "#1f3350",
    headingColor: "#f5f8fb",
  },
  {
    id: "portfolio-clean",
    name: "Portfolio Clean",
    desc: "Pure white canvas, near-black text, neutral borders. Built for commercial portfolios where the work is the color.",
    mode: "light",
    primaryColor: "#ffffff",
    cardBgColor: "#f8f8f8",
    accentColor: "#111111",
    bodyTextColor: "#555555",
    borderColor: "#e4e4e4",
    headingColor: "#111111",
  },
];

// ──────────────────────────────────────────────────────────────────────────────
// LAYOUTS — distinct structural/typographic personalities. Independent of color.
// Picks the size, spacing, alignment, and ornamental treatment for each section.
// Inspired by reference sites:
// - Editorial Minimal: Rosalie, Lustre, Breef
// - Editorial Bold: Faure, Nevo
// - Magazine: Print-inspired editorials
// - Studio Modern: Refined card-based studios
// - Brutalist: Raw, oversized experimental
// ──────────────────────────────────────────────────────────────────────────────