// Converts external brand data (Blueprint Library builds, and eventually
// Style Guide's brand_styles) into Template Studio's actual color/font
// shape. Both external sources store colors using the identical 8-key
// vocabulary (ink/brass/brass-deep/bone/asphalt/stone/warm-white/text) --
// confirmed by reading both api/brand-styles.js's ROLE_TO_KEY mapping and
// src/brief-to-blueprint/utils/library.js's saved entry shape directly,
// not assumed. Template Studio's real, rendering-driving fields (confirmed
// via applyTheme() in constants/templates.js, not the docs) are
// primaryColor/accentColor/cardBgColor/bodyTextColor/borderColor +
// headingFont/bodyFont.

// Same luminance-based check already used in index.jsx's isCustom color-
// application branch, duplicated here rather than imported since that
// logic isn't currently exported from anywhere -- kept identical so
// borderColor derivation behaves exactly the same way it already does for
// AI-generated custom projects.
function isColorDark(hex) {
  if (!hex || typeof hex !== "string") return false;
  const h = hex.replace("#", "");
  if (h.length < 6) return false;
  const r = parseInt(h.slice(0, 2), 16), g = parseInt(h.slice(2, 4), 16), b = parseInt(h.slice(4, 6), 16);
  if ([r, g, b].some(Number.isNaN)) return false;
  return (0.299 * r + 0.587 * g + 0.114 * b) / 255 < 0.5;
}

function isValidHex(s) {
  return typeof s === "string" && /^#[0-9a-f]{6}$/i.test(s);
}

// Same pattern-matching as api/_lib/computedFontStyle.js's internal
// looksAutoGenerated() (not exported from there, and that file is server-
// only -- duplicated intentionally rather than introducing an api/_lib ->
// src/utils import that has no existing precedent in this codebase).
// Catches Wix's "wfont_<hex>_<hex>" and Next.js's "__fontname_<hex>"
// patterns -- real risk here specifically because Blueprint Library
// entries can originate from Manifest imports or site-crawl data, the
// same kind of extracted-from-a-live-site font name that was already
// confirmed to produce exactly this garbage in Style Guide's own
// extraction pipeline.
function looksAutoGeneratedFontName(name) {
  if (!name) return false;
  if (/_[0-9a-f]{6,}/i.test(name)) return true;
  if (name.length > 40) return true;
  if (name.includes("_") && !name.includes(" ")) return true;
  return false;
}

// fonts may be an array [heading, body] (Blueprint Library's shape,
// confirmed in library.js: `fonts: brief.fonts || []`) or an object
// {heading, body} (brand_styles' shape, confirmed in brand-styles.js's
// save handler converting from B2B's array on the way in). Accepts
// either so this same function covers both external sources.
function extractHeadingBody(fonts) {
  if (Array.isArray(fonts)) return { heading: fonts[0], body: fonts[1] };
  if (fonts && typeof fonts === "object") return { heading: fonts.heading, body: fonts.body };
  return { heading: null, body: null };
}

// Pure, no side effects, never throws. Returns a complete, safe
// { primaryColor, accentColor, cardBgColor, bodyTextColor, borderColor,
// headingFont, bodyFont } object regardless of how incomplete or
// malformed the input is -- every field always falls back to a sane
// default rather than ever producing undefined, an empty string, or a
// value that would break rendering (an invalid hex, a garbled font name).
export function mapExternalBrandToTemplateStudio(colors, fonts) {
  const c = colors || {};
  const ink = isValidHex(c.ink) ? c.ink : null;
  const brass = isValidHex(c.brass) ? c.brass : null;
  const bone = isValidHex(c.bone) ? c.bone : null;
  const text = isValidHex(c.text) ? c.text : null;

  const dark = ink ? isColorDark(ink) : false;

  const { heading, body } = extractHeadingBody(fonts);
  const safeHeading = heading && !looksAutoGeneratedFontName(heading) ? heading : "Inter";
  const safeBody = body && !looksAutoGeneratedFontName(body) ? body : "Inter";

  return {
    primaryColor: ink || "#ffffff",
    accentColor: brass || "#111111",
    cardBgColor: bone || (dark ? "#181818" : "#f7f7f5"),
    bodyTextColor: text || (dark ? "#a8a8a8" : "#4a4a4a"),
    borderColor: dark ? "#2a2a2a" : "#e8e8e6",
    headingFont: safeHeading,
    bodyFont: safeBody,
  };
}
